### PR TITLE
Fix config keywordize issue in Serde class

### PR DESCRIPTION
**Pull request by k2n**
Hi, 

First, thank you for sharing this project. I tried to implement Serde and struggled with `gen-class`, and then found your project while seeking a clue.  I saw you already implement it elegantly and saved my day!

I tried to use `0.9.1-SNAPSHOT`, but noticed `schema-registry-client` and `serializer` configs are not recognized, and I got an error on deserialization. See https://github.com/parkside-securities/kafka-avro-confluent/issues/1 

Please consider merging this so we can keep using your project rather than our fork. I confirmed serialization by Kafka producer, and deserialization by Serde, but haven't tested other permutations yet. 

Cheers,

### CODE REVIEW

**Comment by k2n** [comment]
Hi, 
I use kafka 1.1.0, and got the following exception if I pass in the instance returned from `Serdes/serdeFrom` to `value.serde` config. 

```
ConfigException Invalid value org.apache.kafka.common.serialization.Serdes$WrapperSerde@656fcf12 for configuration value.serde: Expected a Class instance or class name.  org.apache.kafka.common.config.ConfigDef.parseType (ConfigDef.java:717)
```
As far as I see, `parseType` accepts only primitives and Class, not an instance of Serde object. 

```java
    public static Object parseType(String name, Object value, Type type) {
        try {
            if (value == null) return null;

            String trimmed = null;
            if (value instanceof String)
                trimmed = ((String) value).trim();

            switch (type) {
                case BOOLEAN:
                    if (value instanceof String) {
                ...
                case CLASS:
                    if (value instanceof Class)
                        return value;
                    else if (value instanceof String)
                        return Class.forName(trimmed, true, Utils.getContextOrKafkaClassLoader());
                    else
                        throw new ConfigException(name, value, "Expected a Class instance or class name.");
```
If I call `.getClass` then I get an error complaining missing default constructor. 
```clojure
(defmethod ig/init-key :kafka-streams/serde [_ {:keys [serializer deserializer]}]
  (.getClass (Serdes/serdeFrom serializer deserializer)))
```

```
Caused by: org.apache.kafka.streams.errors.StreamsException: Failed to configure value serde class org.apache.kafka.common.serialization.Serdes$WrapperSerde
        at org.apache.kafka.streams.StreamsConfig.defaultValueSerde(StreamsConfig.java:972)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.<init>(AbstractProcessorContext.java:59)
...
Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.serialization.Serdes$WrapperSerde
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:297)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:302)
        at org.apache.kafka.streams.StreamsConfig.defaultValueSerde(StreamsConfig.java:963)
        ... 19 more
Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.serialization.Serdes$WrapperSerde.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getDeclaredConstructor(Class.java:2178)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:295)
        ... 21 more
```

I interpreted Kafka requires a custom class that implements `Serde` interface with `configure` method containing the logic, and that's why started to write `gen-class`...

I checked out 1.0 branch's `ConfigDef.java`, and it looks same with 1.1. How did you specify the Serde to config? 

Thanks,

**Comment by vise890-ovo** [comment]
I guess we don't use the config much, we do all the setup with the builder. Here's a more complete example

```clojure
(ns flow-platform-reconciliation.kafka.event-stream
  (:require [clojure.tools.logging :as log]
            [flow-platform-reconciliation.entity-seen-store :refer [mark-as-seen]]
            [flow-platform-reconciliation.kafka.config :as kafka-config]
            [iapetos.core :as prometheus]
            [integrant.core :as ig]
            [kafka-avro-confluent.deserializers :refer [->avro-deserializer]])
  (:import org.apache.kafka.clients.consumer.ConsumerConfig
           [org.apache.kafka.common.serialization Serdes Serializer]
           [org.apache.kafka.streams Consumed KafkaStreams KeyValue StreamsBuilder StreamsConfig]
           [org.apache.kafka.streams.kstream ForeachAction Transformer TransformerSupplier]))

(deftype UnimplementedAvroSerializer []
  org.apache.kafka.common.serialization.Serializer
  (configure [_ _ _])
  (serialize [_ _ _] (UnsupportedOperationException. "This serializer should not be called"))
  (close [_]))

(defn init-stream
  [{:keys [application-id
           kafka-config
           topics
           schema-registry-client
           db]}]
  (let [config         (-> kafka-config
                           (merge {StreamsConfig/APPLICATION_ID_CONFIG     application-id
                                   ConsumerConfig/AUTO_OFFSET_RESET_CONFIG "earliest"})
                           (kafka-config/normalize-config)
                           (StreamsConfig.))
        stream-builder (StreamsBuilder.)
        key-serde      (Serdes/String)
        value-serde    (Serdes/serdeFrom (->UnimplementedAvroSerializer) ;; NOTE it only reads!
                                         (->avro-deserializer schema-registry-client))]
    (-> stream-builder
        (.stream topics (Consumed/with key-serde value-serde))
        (.foreach (->SomeAction db)))
    (doto (KafkaStreams. (.build stream-builder) config)
      (.setUncaughtExceptionHandler (StreamsExceptionHandler.))
      (.start))))

(defmethod ig/init-key ::event-stream
  [_ opts]
  (let [s (init-stream opts)]
    (log/info "Event stream started")
    s))

(defmethod ig/halt-key! ::event-stream [_ stream] (some-> stream .close))
```

**Comment by vise890-ovo** [comment]
Actually it's such a small change, i've merged it

**Comment by k2n** [comment]
Thanks for sharing the usage, it was very helpful. I was stuck with the idea to pass via `key.serde` and `value.serde`, but obviously, your approach is more flexible. I could integrate Serde without `gen-class` as well. I agree that it is useful for some cases so I hope it is kept maintained. Again, thanks for your help!

**Pull request merged**
